### ISSUE TITLE
Issue: Regarding Angular Project

### ISSUE THREAD

**Issue by varunshankar07** [dameeta/AngularRepositoryNov23#1]
Good Evening Mam, my name is varun i am a student from you techfortune internship, could you please enlighten me on what project you gave on angular, due to some reasons i was not able to attend some classes, it would nice of you if you share what project/assignment i have to make on angular

**Comment by Manojsullad1** [comment]
Good Evening Mam, my name is manoj i am a student from you techfortune internship, could you please enlighten me on what project you gave on angular, due to some reasons i was not able to attend some classes, it would nice of you if you share what project/assignment i have to make on angular

**Comment by varunshankar07** [comment]
@dameeta any updates mam!
